# Generated by Django 5.1.1 on 2024-09-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
