# Generated by Django 5.0.6 on 2024-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_cabinet_email_cabinet_facebook_cabinet_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='type',
            field=models.IntegerField(choices=[(0, 'CLUBS'), (1, 'TECH TEAM'), (2, 'OTHER BODIES')]),
        ),
    ]
