# Generated by Django 5.1.1 on 2024-10-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatements',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problemstatements',
            name='img',
        ),
        migrations.RemoveField(
            model_name='problemstatements',
            name='link',
        ),
    ]
