# Generated by Django 5.1.1 on 2024-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_problemstatements_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiit',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
